# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93b3c7b3edc278675fa85bf6b6995a962caaba68ee2d29bc9ced048d6e8bd3877bf980225200b075c3961ba794e683f2d751e3abcb31c2ea329d485c311cd4bd

test:
  secret_key_base: 1cf9ede8f0768187be79aa719d416f11408cfd8131923b092a890c575882882b442ec57f7b61e5897b9e6c17287390548a8c6bbbca0894f06ce691ff24b620d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
